//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 
namespace iLabs.Proxies.ILS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="I_ILS", Namespace="http://ilab.mit.edu/iLabs/Services")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationHeader))]
    public partial class InteractiveLSProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public AgentAuthHeader AgentAuthHeaderValue;
        
        private System.Threading.SendOrPostCallback AlertOperationCompleted;
        
        /// <remarks/>
        public InteractiveLSProxy() {
            this.Url = "http://localhost/ilab_WSDL/I_ILS.asmx";
        }
        
        /// <remarks/>
        public event AlertCompletedEventHandler AlertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AgentAuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ilab.mit.edu/iLabs/Services/Alert", RequestNamespace="http://ilab.mit.edu/iLabs/Services", ResponseNamespace="http://ilab.mit.edu/iLabs/Services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Alert(string payload) {
            this.Invoke("Alert", new object[] {
                        payload});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAlert(string payload, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Alert", new object[] {
                        payload}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAlert(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void AlertAsync(string payload) {
            this.AlertAsync(payload, null);
        }
        
        /// <remarks/>
        public void AlertAsync(string payload, object userState) {
            if ((this.AlertOperationCompleted == null)) {
                this.AlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlertOperationCompleted);
            }
            this.InvokeAsync("Alert", new object[] {
                        payload}, this.AlertOperationCompleted, userState);
        }
        
        private void OnAlertOperationCompleted(object arg) {
            if ((this.AlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ilab.mit.edu/iLabs/type", IsNullable=false)]
    public partial class AgentAuthHeader : AuthenticationHeader {
        
        /// <remarks/>
        public string agentGuid;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgentAuthHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public Coupon coupon;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ilab.mit.edu/iLabs/type")]
    public partial class Coupon {
        
        /// <remarks/>
        public long couponId;
        
        /// <remarks/>
        public string issuerGuid;
        
        /// <remarks/>
        public string passkey;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void AlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
